name: CI/CD Laravel - Backend Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql, mbstring
          coverage: none

      - name: Composer cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: install

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.DB_DATABASE }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - ${{ secrets.DB_PORT }}:${{ secrets.DB_PORT }}
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set environment and run migrations
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run tests
        run: php artisan test

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: DockerHub login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t saas-backend:production .

      - name: Tag and push image
        run: |
          docker tag saas-backend:production ${{ secrets.DOCKERHUB_USERNAME }}/saas-backend:production
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/saas-backend:production

          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag saas-backend:production ${{ secrets.DOCKERHUB_USERNAME }}/saas-backend:$SHORT_SHA
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/saas-backend:$SHORT_SHA
